name: Build themes

on:
  registry_package:
    action:
      - updated
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build-themes.yml'

jobs:
  build-themes:
    name: Build Storefront themes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci --only=production

      - name: Run build
        run: npm run build:themes
        
      - name: Push to branch theme-dist to trigger deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: themes-dist
          FOLDER: .deploy/themes
          CLEAN: true
