name: Compress images

on: pull_request

jobs:
  compress-images:
    name: Try to optimize repo image files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Optimize with Calibre's image actions
        uses: docker://calibreapp/github-image-actions@sha256:9d89c56573a3923b35b275970cafde7edeed54cb86849d384fc1e66142997fa9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
