name: Compress images

on: pull_request

jobs:
  compress-images:
    name: Try to optimize repo image files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Optimize with Calibre's image actions
        uses: docker://calibreapp/github-image-actions@sha256:8a175ee6d52f07052e9ddb4c13fb3bd7f5c357aad994b034f7c12c474b8ca6cd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
