name: Publish

on: registry_package

jobs:
  deploy:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Edit package.json and publish to npm registry
        env:
          PKG_OWNER: ${{ github.event.registry_package.owner.login }}
          PKG_NAME: ${{ github.event.registry_package.name }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ./@$PKG_OWNER/$PKG_NAME && \
          node -p "const pkg = require('./package.json'); \
          if (pkg.publishConfig) delete pkg.publishConfig.registry; \
          JSON.stringify(pkg, null, 2)" > pkg.json && mv pkg.json package.json && \
          npm ci && npm run build && npm publish
